/**
 * Centralized 301 redirects for WordPress → Next.js migration.
 *
 * HOW TO USE:
 * Add entries to the array below. Each entry needs:
 *   source:      The old WordPress URL path (with trailing slash if needed)
 *   destination: The new Next.js URL path
 *   permanent:   true (301 redirect, always)
 *
 * This file is imported by next.config.mjs.
 * You can paste large batches of URLs here without cluttering the main config.
 * 
 * Auto-generated by generate-redirects.js on 2026-05-12
 */

const redirects = [
  // ── Legacy route redirects ──────────────────────────────────────
  {
    source: '/tutorials',
    destination: '/blog',
    permanent: true,
  },
  {
    source: '/tutoriales',
    destination: '/blog',
    permanent: true,
  },
  {
    source: '/tutorials/:path*',
    destination: '/blog',
    permanent: true,
  },

  // ── WordPress post → Next.js silo redirects (auto-generated) ──
  {
    source: '/politica-de-privacidad/',
    destination: '/privacy/',
    permanent: true,
  },
  {
    source: '/contacto/',
    destination: '/contact/',
    permanent: true,
  },
  {
    source: '/acerca-de/',
    destination: '/about/',
    permanent: true,
  },
  {
    source: '/diseno-bluey-bingo-cumpleanos-sublimacion-playeras/',
    destination: '/dtf/diseno-bluey-bingo-cumpleanos-sublimacion-playeras/',
    permanent: true,
  },
  {
    source: '/diseno-de-mis-pastelitos-para-tutus-personalizados/',
    destination: '/dtf/diseno-de-mis-pastelitos-para-tutus-personalizados/',
    permanent: true,
  },
  {
    source: '/diseno-de-justin-bieber-para-conciertos/',
    destination: '/dtf/diseno-de-justin-bieber-para-conciertos/',
    permanent: true,
  },
  {
    source: '/diseno-de-la-abejita-plim-plim-para-cumpleanos/',
    destination: '/dtf/diseno-de-la-abejita-plim-plim-para-cumpleanos/',
    permanent: true,
  },
  {
    source: '/diseno-de-shakira-las-mujeres-ya-no-lloran-world-tour/',
    destination: '/dtf/diseno-de-shakira-las-mujeres-ya-no-lloran-world-tour/',
    permanent: true,
  },
  {
    source: '/diseno-gratuito-de-plim-plim-para-proyectos-infantiles/',
    destination: '/dtf/diseno-gratuito-de-plim-plim-para-proyectos-infantiles/',
    permanent: true,
  },
  {
    source: '/diseno-gratuito-de-gallina-pintadita-en-tonos-pastel/',
    destination: '/dtf/diseno-gratuito-de-gallina-pintadita-en-tonos-pastel/',
    permanent: true,
  },
  {
    source: '/diseno-gratuito-de-niall-horan-the-show-para-conciertos/',
    destination: '/dtf/diseno-gratuito-de-niall-horan-the-show-para-conciertos/',
    permanent: true,
  },
  {
    source: '/diseno-de-bluey-bingo-y-familia-para-fiesta-de-cumpleanos/',
    destination: '/dtf/diseno-de-bluey-bingo-y-familia-para-fiesta-de-cumpleanos/',
    permanent: true,
  },
  {
    source: '/diseno-darth-vader-sublimacion-dtf-vinil-y-corte-en-plotter/',
    destination: '/dtf/diseno-darth-vader-sublimacion-dtf-vinil-y-corte-en-plotter/',
    permanent: true,
  },
  {
    source: '/diseno-del-rayo-mcqueen-plantilla-para-sublimacion-dtf-y-corte-de-vinil/',
    destination: '/dtf/diseno-del-rayo-mcqueen-plantilla-para-sublimacion-dtf-y-corte-de-vinil/',
    permanent: true,
  },
  {
    source: '/diseno-gratuito-plantilla-de-sally-carrera-para-sublimacion-y-corte-de-vinil/',
    destination: '/sublimacion/diseno-gratuito-plantilla-de-sally-carrera-para-sublimacion-y-corte-de-vinil/',
    permanent: true,
  },
  {
    source: '/diseno-de-stitch-para-sublimacion-dtf-y-vinil-textil/',
    destination: '/sublimacion/diseno-de-stitch-para-sublimacion-dtf-y-vinil-textil/',
    permanent: true,
  },
  {
    source: '/diseno-itachi-akatsuki-vector-gratis/',
    destination: '/dtf/diseno-itachi-akatsuki-vector-gratis/',
    permanent: true,
  },
  {
    source: '/diseno-gratis-debi-tirar-mas-fotos-bad-bunny-para-sublimacion-dtf/',
    destination: '/',
    permanent: true,
  },
  {
    source: '/diseno-gratis-rugrats-para-sublimacion-playeras-dtf/',
    destination: '/dtf/diseno-gratis-rugrats-para-sublimacion-playeras-dtf/',
    permanent: true,
  },
  {
    source: '/programas-editar-archivos-ai-psd-png-studio3/',
    destination: '/blog/programas-editar-archivos-ai-psd-png-studio3/',
    permanent: true,
  },
  {
    source: '/arte-para-sublimacion-album-bad-bunny-diseno-gratis-dtf/',
    destination: '/dtf/arte-para-sublimacion-album-bad-bunny-diseno-gratis-dtf/',
    permanent: true,
  },
  {
    source: '/diseno-gratis-bad-bunny-debi-tirar-mas-fotos-tercera-version/',
    destination: '/',
    permanent: true,
  },
  {
    source: '/pack-disenos-dia-de-las-madres-gratis/',
    destination: '/dtf/pack-disenos-dia-de-las-madres-gratis/',
    permanent: true,
  },
  {
    source: '/diseno-lilo-stitch-dtf-sublimacion-gratis/',
    destination: '/dtf/diseno-lilo-stitch-dtf-sublimacion-gratis/',
    permanent: true,
  },
  {
    source: '/disenar-imagenes-gratis-online/',
    destination: '/blog/disenar-imagenes-gratis-online/',
    permanent: true,
  },
  {
    source: '/pack-diseno-el-mejor-papa-del-mundo-gratis-10-formatos/',
    destination: '/dtf/pack-diseno-el-mejor-papa-del-mundo-gratis-10-formatos/',
    permanent: true,
  },
  {
    source: '/pack-disenos-stitch-sublimacion-corte-gratis/',
    destination: '/dtf/pack-disenos-stitch-sublimacion-corte-gratis/',
    permanent: true,
  },
  {
    source: '/sublimacion-diseno-papa-superheroe-sublimacion-gratis-10-formatos/',
    destination: '/dtf/sublimacion-diseno-papa-superheroe-sublimacion-gratis-10-formatos/',
    permanent: true,
  },
  {
    source: '/como-usar-disenos-sublimacion/',
    destination: '/blog/como-usar-disenos-sublimacion/',
    permanent: true,
  },
  {
    source: '/diseno-dia-del-padre-padre-y-abuelo-gratis/',
    destination: '/dtf/diseno-dia-del-padre-padre-y-abuelo-gratis/',
    permanent: true,
  },
  {
    source: '/diseno-papa-e-hijos-dia-del-padre-gratis/',
    destination: '/dtf/diseno-papa-e-hijos-dia-del-padre-gratis/',
    permanent: true,
  },
  {
    source: '/diseno-gratis-primer-dia-del-padre-para-sublimar/',
    destination: '/dtf/diseno-gratis-primer-dia-del-padre-para-sublimar/',
    permanent: true,
  },
  {
    source: '/disenos-gratis-para-dtf-que-venden/',
    destination: '/blog/disenos-gratis-para-dtf-que-venden/',
    permanent: true,
  },
  {
    source: '/diseno-labubu-sublimacion-playeras-tazas-ai-eps-png/',
    destination: '/sublimacion/diseno-labubu-sublimacion-playeras-tazas-ai-eps-png/',
    permanent: true,
  },
  {
    source: '/logo-pokemon-png-gratis-descarga/',
    destination: '/dtf/logo-pokemon-png-gratis-descarga/',
    permanent: true,
  },
  {
    source: '/imagen-png-stitch-fondo-transparente-gratis/',
    destination: '/recursos-graficos/imagen-png-stitch-fondo-transparente-gratis/',
    permanent: true,
  },
  {
    source: '/impresion-dtf-playeras/',
    destination: '/blog/impresion-dtf-playeras/',
    permanent: true,
  },
  {
    source: '/imagen-png-goku-fondo-transparente-gratis/',
    destination: '/sublimacion/imagen-png-goku-fondo-transparente-gratis/',
    permanent: true,
  },
  {
    source: '/lalo-y-stitch-semitono-png-gratis-para-dtf/',
    destination: '/dtf/lalo-y-stitch-semitono-png-gratis-para-dtf/',
    permanent: true,
  },
  {
    source: '/personajes-mario-bros-png-disenos-sublimar-dtf-gratis/',
    destination: '/dtf/personajes-mario-bros-png-disenos-sublimar-dtf-gratis/',
    permanent: true,
  },
  {
    source: '/como-se-hacen-nuestros-disenos/',
    destination: '/',
    permanent: true,
  },
  {
    source: '/plantilla-taza-harry-styles-descarga-gratis-sublimacion/',
    destination: '/sublimacion/plantilla-taza-harry-styles-descarga-gratis-sublimacion/',
    permanent: true,
  },
  {
    source: '/vectores-los-4-fantasticos-para-sublimacion/',
    destination: '/sublimacion/vectores-los-4-fantasticos-para-sublimacion/',
    permanent: true,
  },
  {
    source: '/plantilla-taza-labubu-real-psg-bayern/',
    destination: '/sublimacion/plantilla-taza-labubu-real-psg-bayern/',
    permanent: true,
  },
  {
    source: '/bandera-mexico-png-brochazos-fondo-transparente/',
    destination: '/recursos-graficos/bandera-mexico-png-brochazos-fondo-transparente/',
    permanent: true,
  },
  {
    source: '/viva-mexico-lettering-descarga-gratis/',
    destination: '/sublimacion/viva-mexico-lettering-descarga-gratis/',
    permanent: true,
  },
  {
    source: '/squirtle-japones-semitonos-dtf-png-gratis/',
    destination: '/dtf/squirtle-japones-semitonos-dtf-png-gratis/',
    permanent: true,
  },
  {
    source: '/virgen-guadalupe-semitonos-dtf-png-gratis/',
    destination: '/dtf/virgen-guadalupe-semitonos-dtf-png-gratis/',
    permanent: true,
  },
  {
    source: '/foto-instantanea-polaroid-png-gratis/',
    destination: '/recursos-graficos/foto-instantanea-polaroid-png-gratis/',
    permanent: true,
  },
  {
    source: '/pack-disenos-dtf-gratis-png-semitonos/',
    destination: '/dtf/pack-disenos-dtf-gratis-png-semitonos/',
    permanent: true,
  },
  {
    source: '/pack-fondos-virtuales-zoom-meet-teams-gratis/',
    destination: '/fondos-y-texturas/pack-fondos-virtuales-zoom-meet-teams-gratis/',
    permanent: true,
  },
  {
    source: '/como-sublimar-guia-paso-a-paso/',
    destination: '/blog/como-sublimar-guia-paso-a-paso/',
    permanent: true,
  },
  {
    source: '/pack-paisajes-naturaleza-descargar-imagen-de-paisaje/',
    destination: '/fondos-y-texturas/pack-paisajes-naturaleza-descargar-imagen-de-paisaje/',
    permanent: true,
  },
  {
    source: '/tipografias-halloween-gratis-pack-ttf/',
    destination: '/tipografias/tipografias-halloween-gratis-pack-ttf/',
    permanent: true,
  },
  {
    source: '/charmander-japones-semitonos-dtf-png-gratis/',
    destination: '/dtf/charmander-japones-semitonos-dtf-png-gratis/',
    permanent: true,
  },
  {
    source: '/bandas-en-color-magenta-dtf-solucion/',
    destination: '/blog/bandas-en-color-magenta-dtf-solucion/',
    permanent: true,
  },
  {
    source: '/como-imprimir-foto-con-celular-en-dtf/',
    destination: '/blog/como-imprimir-foto-con-celular-en-dtf/',
    permanent: true,
  },
  {
    source: '/como-sublimar-una-playera-guia-practica-2025/',
    destination: '/blog/como-sublimar-una-playera-guia-practica-2025/',
    permanent: true,
  },
  {
    source: '/personajes-de-halloween-vector-infantil-calabaza-bruja-vampiro-calavera-esqueleto/',
    destination: '/sublimacion/personajes-de-halloween-vector-infantil-calabaza-bruja-vampiro-calavera-esqueleto/',
    permanent: true,
  },
  {
    source: '/pack-de-velas-png-fondo-transparente/',
    destination: '/recursos-graficos/pack-de-velas-png-fondo-transparente/',
    permanent: true,
  },
  {
    source: '/plantilla-de-loteria-mexicana-para-imprimir-editar-y-sublimar/',
    destination: '/plantillas/plantilla-de-loteria-mexicana-para-imprimir-editar-y-sublimar/',
    permanent: true,
  },
  {
    source: '/invitacion-cumpleanos-editable-dragon-ball/',
    destination: '/plantillas/invitacion-cumpleanos-editable-dragon-ball/',
    permanent: true,
  },
  {
    source: '/mejores-marcas-de-playeras-para-sublimacion-y-serigrafia/',
    destination: '/blog/mejores-marcas-de-playeras-para-sublimacion-y-serigrafia/',
    permanent: true,
  },
  {
    source: '/plantilla-invitacion-baby-shower-borreguito/',
    destination: '/plantillas/plantilla-invitacion-baby-shower-borreguito/',
    permanent: true,
  },
  {
    source: '/pack-disenos-para-tazas-navidenas-pdf-png/',
    destination: '/sublimacion/pack-disenos-para-tazas-navidenas-pdf-png/',
    permanent: true,
  },
  {
    source: '/sigue-siendo-negocio-la-sublimacion-en-2025/',
    destination: '/blog/sigue-siendo-negocio-la-sublimacion-en-2025/',
    permanent: true,
  },
  {
    source: '/fondos-de-navidad-png-gratis/',
    destination: '/fondos-y-texturas/fondos-de-navidad-png-gratis/',
    permanent: true,
  },
  {
    source: '/logos-dragon-ball-png/',
    destination: '/recursos-graficos/logos-dragon-ball-png/',
    permanent: true,
  },
  {
    source: '/logo-one-piece-png-wanted-posters/',
    destination: '/sublimacion/logo-one-piece-png-wanted-posters/',
    permanent: true,
  },
  {
    source: '/adios-a-los-datos-aburridos-tu-guia-secreta-para-disenar-infografias-irresistibles/',
    destination: '/blog/adios-a-los-datos-aburridos-tu-guia-secreta-para-disenar-infografias-irresistibles/',
    permanent: true,
  },
  {
    source: '/20-plantillas-gratis-para-mugs-de-amor-y-amistad-descarga-png/',
    destination: '/sublimacion/20-plantillas-gratis-para-mugs-de-amor-y-amistad-descarga-png/',
    permanent: true,
  }
]

export default redirects
