import type { Design, Tutorial, BlogPost, Category } from './types'

export const mockCategories: Category[] = [
  { id: '1', name: 'Social Media', slug: 'social-media', description: 'Templates for Instagram, TikTok, and more', icon: 'Share2' },
  { id: '2', name: 'Presentations', slug: 'presentations', description: 'Professional presentation templates', icon: 'Presentation' },
  { id: '3', name: 'Fonts', slug: 'fonts', description: 'Premium and free fonts', icon: 'Type' },
  { id: '4', name: 'Video Templates', slug: 'video-templates', description: 'CapCut and video editing templates', icon: 'Video' },
  { id: '5', name: 'Brand Kits', slug: 'brand-kits', description: 'Complete branding packages', icon: 'Palette' },
  { id: '6', name: 'Print Design', slug: 'print-design', description: 'Flyers, posters, and more', icon: 'Printer' },
]

export const mockDesigns: Design[] = [
  {
    id: '1',
    title: 'Minimal Instagram Story Pack',
    description: 'Clean and modern Instagram story templates perfect for lifestyle brands and influencers.',
    slug: 'minimal-instagram-story-pack',
    thumbnail_url: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=600&h=800&fit=crop',
    category: 'social-media',
    type: 'canva',
    external_url: 'https://canva.com/templates/example',
    is_vip: false,
    downloads: 1234,
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-01-15T10:00:00Z',
    tags: ['instagram', 'stories', 'minimal', 'social media']
  },
  {
    id: '2',
    title: 'Neon Gradient Reel Templates',
    description: 'Eye-catching neon gradient templates for Instagram Reels and TikTok videos.',
    slug: 'neon-gradient-reel-templates',
    thumbnail_url: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&h=800&fit=crop',
    category: 'video-templates',
    type: 'capcut',
    external_url: 'https://capcut.com/templates/example',
    premium_url: 'https://premium.example.com/neon-gradient',
    is_vip: true,
    downloads: 892,
    created_at: '2024-01-14T10:00:00Z',
    updated_at: '2024-01-14T10:00:00Z',
    tags: ['reels', 'tiktok', 'neon', 'gradient', 'video']
  },
  {
    id: '3',
    title: 'Elegant Serif Font Bundle',
    description: 'A beautiful collection of elegant serif fonts for branding and editorial design.',
    slug: 'elegant-serif-font-bundle',
    thumbnail_url: 'https://images.unsplash.com/photo-1618556450994-a6a128ef0d9d?w=600&h=800&fit=crop',
    category: 'fonts',
    type: 'font',
    download_url: '/downloads/elegant-serif-bundle.zip',
    premium_url: 'https://premium.example.com/elegant-serif',
    is_vip: true,
    downloads: 2567,
    created_at: '2024-01-13T10:00:00Z',
    updated_at: '2024-01-13T10:00:00Z',
    tags: ['fonts', 'serif', 'elegant', 'typography']
  },
  {
    id: '4',
    title: 'Business Pitch Deck',
    description: 'Professional pitch deck template for startups and entrepreneurs.',
    slug: 'business-pitch-deck',
    thumbnail_url: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600&h=800&fit=crop',
    category: 'presentations',
    type: 'canva',
    external_url: 'https://canva.com/templates/pitch-deck',
    is_vip: false,
    downloads: 3421,
    created_at: '2024-01-12T10:00:00Z',
    updated_at: '2024-01-12T10:00:00Z',
    tags: ['presentation', 'pitch deck', 'business', 'startup']
  },
  {
    id: '5',
    title: 'Aesthetic TikTok Intro Pack',
    description: 'Trendy and aesthetic intro templates for TikTok creators.',
    slug: 'aesthetic-tiktok-intro-pack',
    thumbnail_url: 'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=600&h=800&fit=crop',
    category: 'video-templates',
    type: 'capcut',
    external_url: 'https://capcut.com/templates/aesthetic-intro',
    is_vip: false,
    downloads: 1876,
    created_at: '2024-01-11T10:00:00Z',
    updated_at: '2024-01-11T10:00:00Z',
    tags: ['tiktok', 'intro', 'aesthetic', 'video']
  },
  {
    id: '6',
    title: 'Modern Sans Font Family',
    description: 'Clean, modern sans-serif font family with multiple weights.',
    slug: 'modern-sans-font-family',
    thumbnail_url: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600&h=800&fit=crop',
    category: 'fonts',
    type: 'font',
    download_url: '/downloads/modern-sans.zip',
    is_vip: false,
    downloads: 4532,
    created_at: '2024-01-10T10:00:00Z',
    updated_at: '2024-01-10T10:00:00Z',
    tags: ['fonts', 'sans-serif', 'modern', 'clean']
  },
  {
    id: '7',
    title: 'Luxury Brand Kit',
    description: 'Complete luxury brand kit with logos, patterns, and social media templates.',
    slug: 'luxury-brand-kit',
    thumbnail_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=800&fit=crop',
    category: 'brand-kits',
    type: 'internal',
    download_url: '/downloads/luxury-brand-kit.zip',
    premium_url: 'https://premium.example.com/luxury-brand',
    is_vip: true,
    downloads: 987,
    created_at: '2024-01-09T10:00:00Z',
    updated_at: '2024-01-09T10:00:00Z',
    tags: ['brand kit', 'luxury', 'branding', 'logo']
  },
  {
    id: '8',
    title: 'Event Flyer Collection',
    description: 'Versatile flyer templates for parties, concerts, and events.',
    slug: 'event-flyer-collection',
    thumbnail_url: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=600&h=800&fit=crop',
    category: 'print-design',
    type: 'canva',
    external_url: 'https://canva.com/templates/flyers',
    is_vip: false,
    downloads: 2134,
    created_at: '2024-01-08T10:00:00Z',
    updated_at: '2024-01-08T10:00:00Z',
    tags: ['flyer', 'event', 'party', 'print']
  },
]

export const mockTutorials: Tutorial[] = [
  {
    id: '1',
    title: 'Create Stunning Reels in CapCut',
    description: 'Learn how to create professional-looking Instagram Reels using CapCut templates.',
    slug: 'create-stunning-reels-capcut',
    youtube_embed_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnail_url: 'https://images.unsplash.com/photo-1611162618071-b39a2ec055fb?w=600&h=400&fit=crop',
    pinterest_url: 'https://pinterest.com/pin/example1',
    tiktok_url: 'https://tiktok.com/@example/video1',
    category: 'video-templates',
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    title: 'Canva Tips for Beginners',
    description: 'Master the basics of Canva with these essential tips and tricks.',
    slug: 'canva-tips-beginners',
    youtube_embed_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnail_url: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=600&h=400&fit=crop',
    pinterest_url: 'https://pinterest.com/pin/example2',
    category: 'social-media',
    created_at: '2024-01-14T10:00:00Z',
    updated_at: '2024-01-14T10:00:00Z',
  },
  {
    id: '3',
    title: 'Font Pairing Masterclass',
    description: 'Learn the art of combining fonts for beautiful typography.',
    slug: 'font-pairing-masterclass',
    youtube_embed_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnail_url: 'https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?w=600&h=400&fit=crop',
    tiktok_url: 'https://tiktok.com/@example/video3',
    category: 'fonts',
    created_at: '2024-01-13T10:00:00Z',
    updated_at: '2024-01-13T10:00:00Z',
  },
]

export const mockBlogPosts: BlogPost[] = [
  {
    id: '1',
    title: '10 Design Trends to Watch in 2024',
    slug: '10-design-trends-2024',
    excerpt: 'Discover the hottest design trends that will dominate the creative industry this year.',
    content: 'Full article content here...',
    featured_image: 'https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=800&h=500&fit=crop',
    author: 'Design Team',
    category: 'trends',
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-01-15T10:00:00Z',
    tags: ['design', 'trends', '2024', 'inspiration']
  },
  {
    id: '2',
    title: 'How to Build a Strong Personal Brand',
    slug: 'build-strong-personal-brand',
    excerpt: 'Learn the essential steps to create a memorable and impactful personal brand.',
    content: 'Full article content here...',
    featured_image: 'https://images.unsplash.com/photo-1493612276216-ee3925520721?w=800&h=500&fit=crop',
    author: 'Brand Expert',
    category: 'branding',
    created_at: '2024-01-14T10:00:00Z',
    updated_at: '2024-01-14T10:00:00Z',
    tags: ['branding', 'personal brand', 'marketing']
  },
  {
    id: '3',
    title: 'The Ultimate Guide to Color Theory',
    slug: 'ultimate-guide-color-theory',
    excerpt: 'Master the fundamentals of color theory to create stunning visual designs.',
    content: 'Full article content here...',
    featured_image: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=800&h=500&fit=crop',
    author: 'Design Team',
    category: 'tutorials',
    created_at: '2024-01-13T10:00:00Z',
    updated_at: '2024-01-13T10:00:00Z',
    tags: ['color theory', 'design basics', 'tutorial']
  },
]
